### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by PandaFoss** [frenchiveruti/desbloqueonetbook#1]
Parece que ya no funciona. No obstante, ¿hay alguna manera de poder obtener el código de desbloqueo usando el HWID y el Boot Tick?

**Comment by frenchiveruti** [comment]
Hola @MaxNeuron , el sistema para serte sincero lo implementé en 2012 y lo migré a github mucho tiempo después del 2014, su funcionamiento era para ser usado exclusivamente dentro de las redes del colegio donde estuviera el servidor de conectar igualdad con idea de "renovar" el periodo de uso de las netbook sin ir al técnico asignado a cada colegio.
El gobierno nacional de cambiemos ha quitado todo soporte a dichos servidores, por lo tanto no se pueden desbloquear con mi página sin dichos servidores.  
Con respecto a tu pregunta especificamente, dependerá de si la escuela donde está registrada la netbook tiene o no todavía habilitado el servidor. En tal caso si, se puede obtener el código simplemente conectandose a la red wi-fi y usando el sitio este.

**Comment by Pookie918** [comment]
pero es posible q rehabilites la pagina de nuevo tipo si es asi por q necesito desbloquear una notebook y bueno por eso la consulta

**Comment by Pookie918** [comment]
ahi una q es rara y es https://desbloqueo.dgp.educ.ar/  esta actualmente pero dicen q es de la nacion y en el 2024 hubo otra q si funcionaba pero los servidores del ministerio calleron y bueno tipo dejo aca el enlace por si las dudad https://desbloqueos.educacioncba.edu.ar/  pero ante todo podes intentar hacer una pagina nueva para q la gente pueda desbloquear las notebook
